openapi: 3.0.3
info:
  title: Personal Blog
  description: Personal Blog
  termsOfService: http://swagger.io/terms/
  contact:
    email: bangvo.5sense.vn@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0
servers:
  - url: http://localhost:8555/api
    description: Local server

tags:
  - name: Authentication
    description: Login & Register & Logout
  - name: User Management
    description: Manage Users
  - name: Author Management
    description: Manage Authors
  - name: Book Categories Management
    description: Manage book categories
  - name: Publisher Management
    description: Manage Publishers

components:
  schemas:
    Jwt:
      type: object
      properties:
        accessToken:
          type: string
          example: "..."
        tokenType:
          type: string
          example: "bearer"
        expiresInMs:
          type: integer
          example: 86400

    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code
        message:
          type: string
          description: Human-readable message
        data:
          type: object
          description: Response data, can be specific to each endpoint
        notFound:
          type: object
          description: Information for 404 (Not Found) response
          properties:
            resource: 
              type: string
              description: Name or type of the resource that was not found
        internalServerError:
          type: object
          description: Information for 500 (Internal Server Error) response
          properties:
            error:
              type: string
              description: Details of the internal server error
        invalidInput:
          type: object
          description: Information for 400 (Bad Request - Invalid Input) response
          properties:
            fields:
              type: array
              items:
                type: string
                description: List of fields with invalid input values
        unauthorized:
          type: object
          description: Information for 401 (Unauthorized) response
          properties:
            error:
              type: string
              description: Details of the unauthorized request

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: bangvo.5sense.vn@gmail.com
        password:
          type: string
          example: admin
      required:
        - email
        - password

    ResetPasswordRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: bangvo.5sense.vn@gmail.com
        password:
          type: string
          example: new_password123
      required:
        - email
        - password

    UserRegistrationRequest:
      type: object
      properties:
        name:
          type: string
          example: Tester
        email:
          type: string
          format: email
          example: tester@gmail.com
        password:
          type: string
          example: abc@#123
      required:
        - name
        - email
        - password

    UserList:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          email:
            type: string

    UserDetails:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    UserUpdateRequest:
      type: object
      properties:
        name:
          type: string
          example: "UpdatedUser"
        email:
          type: string
          example: "updateduser@example.com"
    
    CreateAuthorRequest:
      type: object
      properties:
        full_name:
          type: string
          example: "Windy Max"
        age:
          type: integer
          example: 25
        phone_number:
          type: string
          example: "1234567890"
      required:
        - full_name
        - age
        - phone_number

    UpdateAuthorRequest:
      type: object
      properties:
        full_name:
          type: string
          maxLength: 255
        age:
          type: integer
          minimum: 1
        phone_number:
          type: string
          maxLength: 20
      required:
        - full_name
        - age
        - phone_number
  
    CreateCategoryRequest:
      type: object
      properties:
        name:
          type: string
          example: "Technology"
        description:
          type: string
          example: "Tech-related books"
      required:
        - name
        - description

    UpdateCategoryRequest:
      type: object
      properties:
        name:
          type: string
          example: "Technology"
        description:
          type: string
          example: "Tech-related books"

    CreatePublisherRequest:
      type: object
      properties:
        name:
          type: string
          example: "Publisher X"
        address:
          type: string
          example: "123 Main Street, City"
      required:
        - name
        - address

    UpdatePublisherRequest:
      type: object
      properties:
        name:
          type: string
          example: "Updated Publisher X"
        address:
          type: string
          example: "456 New Street, Town"
      required:
        - name
        - address



  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /authentication/login:
    post:
      tags:
        - Authentication
      summary: Log in an existing user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
  
  /authentication/user/{id}:
      get:
        tags:
          - Authentication
        summary: Get user by ID
        operationId: getUserById
        parameters:
          - name: id
            in: path
            required: true
            description: User ID
            schema:
              type: integer
        responses:
          '200':
            description: User details
            content:
              application/json:
                example:
                  $ref: '#/components/schemas/ApiResponse'
          '404':
            description: User not found
            content:
              application/json:
                example:
                  $ref: '#/components/schemas/ApiResponse'
        security:
          - token: [ ]
  
  /authentication/logout:
    post:
      tags:
        - Authentication
      summary: Log out the current user
      operationId: logoutUser
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]
  
  /users/register:
    post:
      tags:
        - User Management
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /users:
    get:
      tags:
        - User Management
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Users not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /users/update/{id}:
    put:
      tags:
        - User Management
      summary: Update user by ID
      operationId: updateUserById
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdateRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: User not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /users/reset-password/{email}:
    post:
      tags:
        - User Management
      summary: Reset password and send email
      operationId: resetPasswordAndSendEmail
      parameters:
        - name: email
          in: path
          required: true
          description: User's email
          schema:
            type: string
            format: email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset email sent successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: User not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /users/delete:
    delete:
      tags:
        - User Management
      summary: Delete user by ID
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: User not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /authors:
    get:
      tags:
        - Author Management
      summary: Get all authors
      operationId: getAllAuthors
      responses:
        '200':
          description: List of authors
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Authors not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: [ ]

  /authors/create:
    post:
      tags:
        - Author Management
      summary: Create a new author
      operationId: createAuthor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAuthorRequest'
            example:
              full_name: "Windy Max"
              age: 30
              phone_number: "1234567890"
          
      responses:
        '201':
          description: Author created successfully
          content:
            application/json:
              example:
                status: 200
                message: "Author created successfully"
                data:
                  full_name: "Windy Max"
                  age: 25
                  phone_number: "1234567890"
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                status: 400
                message: "Bad request - Invalid input"
                invalidInput:
                  fields:
                    - full_name
                    - age
                    - phone_number
      security:
        - token: []
  
  /authors/update/{id}:
    put:
      tags:
        - Author Management
      summary: Update an existing author
      operationId: updateAuthor
      parameters:
        - name: id
          in: path
          required: true
          description: Author ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthorRequest'
            example:
              full_name: "Updated Windy Max"
              age: 32
              phone_number: "9876543210"
      responses:
        '200':
          description: Author updated successfully
          content:
            application/json:
              example:
                status: 200
                message: "Author updated successfully"
                data:
                  full_name: "Updated Windy Max"
                  age: 32
                  phone_number: "9876543210"
        '404':
          description: Author not found
          content:
            application/json:
              example:
                status: 404
                message: "Author not found"
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                status: 400
                message: "Bad request - Invalid input"
                invalidInput:
                  fields:
                    - full_name
                    - age
                    - phone_number
      security:
        - token: []

  /categories/create:
    post:
      tags:
        - Book Categories Management
      summary: Create a new category
      operationId: createCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
            example:
              name: "Technology"
              description: "Tech-related books"
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              example:
                status: 201
                message: "Category created successfully"
                data:
                  name: "Technology"
                  description: "Tech-related books"
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                status: 400
                message: "Bad request - Invalid input"
                invalidInput:
                  fields:
                    - name
                    - description
      security:
        - token: []

  /categories:
    get:
      tags:
        - Book Categories Management
      summary: Get all categories
      operationId: getAllCategories
      responses:
        '200':
          description: List of categories
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Categories not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: []

  /categories/update/{id}:
    put:
      tags:
        - Book Categories Management
      summary: Update category by ID
      operationId: updateCategoryById
      parameters:
        - name: id
          in: path
          required: true
          description: Category ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryRequest'
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Category not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: []

  /publishers/create:
    post:
      tags:
        - Publisher Management
      summary: Create a new publisher
      operationId: createPublisher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePublisherRequest'
            example:
              name: "Publisher X"
              address: "123 Main Street, City"
      responses:
        '201':
          description: Publisher created successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: []

  /publishers:
    get:
      tags:
        - Publisher Management
      summary: Get all publishers
      operationId: getAllPublishers
      responses:
        '200':
          description: List of publishers
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Publishers not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: []

  /publishers/update/{id}:
    put:
      tags:
        - Publisher Management
      summary: Update publisher by ID
      operationId: updatePublisherById
      parameters:
        - name: id
          in: path
          required: true
          description: Publisher ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePublisherRequest'
      responses:
        '200':
          description: Publisher updated successfully
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Publisher not found
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              example:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - token: []















